"use strict";
window.ByteBackShop = (() => {
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const options={brand:['Apple','Dell','Lenovo','HP','ASUS','Acer','Microsoft'],os:['macOS','Windows','Linux','iPadOS'],cpu:['Intel','AMD','Apple silicon'],gpu:['Intel','AMD','NVIDIA','Apple']};
  function card(p,{reserve=false}={}) {
    return `<article class="product-card" data-product="${esc(p.id)}"><a class="product-image" href="app.html?item=${encodeURIComponent(p.id)}#catalog" tabindex="${reserve?'-1':'0'}" aria-label="View ${esc(p.name)}">${p.photo ? `<img src="${esc(p.photo)}" alt="${esc(p.name)} — reference photograph" loading="lazy" width="600" height="420">` : '<span class="no-product-photo">Photo not yet provided</span>'}<span class="product-badge">${esc(p.badge||'Community donation')}</span></a><div class="product-body"><div class="product-brand">${esc(p.brand||'Computer')} <span>· ${esc(p.os||'OS not listed')}</span></div><h3>${esc(p.name)}</h3><p class="product-specs">${esc(p.specs)}</p><div class="spec-chips">${[p.cpu,p.gpu==='NVIDIA'?'NVIDIA graphics':p.ram?`${p.ram} GB RAM`:null,p.screen].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')}</div>${p.student_note?`<blockquote class="donor-note">“${esc(p.student_note)}”<cite>— ${esc(p.donor_name)}</cite></blockquote>`:''}<div class="product-buy"><div><span class="product-price">${p.price?'$'+p.price:'Free'}</span><span class="price-caption">${p.price?'at local pickup':'community donation'}</span></div>${reserve?`<button class="button" type="button" data-reserve="${esc(p.id)}">Reserve <span aria-hidden="true">↗</span></button>`:`<a class="product-link" href="app.html?item=${encodeURIComponent(p.id)}#catalog">View computer <span aria-hidden="true">↗</span></a>`}</div></div></article>`;
  }
  function filters(params=new URLSearchParams()) {
    const select=(key,label)=>`<label>${label}<select data-shop-filter="${key}" id="filter-${key}"><option value="">All ${label.toLowerCase()}</option>${options[key].map(v=>`<option value="${esc(v)}" ${params.get(key)===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
    return `<form class="catalog-search" id="catalog-search-form"><label class="sr-only" for="catalog-search">Search computers</label><input id="catalog-search" type="search" value="${esc(params.get('q')||'')}" placeholder="Search ThinkPad, Ryzen, MacBook…"><button class="button" type="submit">Search</button></form><div class="catalog-filter-grid">${select('brand','Brands')}${select('os','Operating systems')}${select('cpu','Processors')}${select('gpu','Graphics')}<label>Budget<select data-shop-filter="budget" id="filter-budget"><option value="">Any price</option>${[100,200,300,500].map(n=>`<option value="${n}" ${params.get('budget')==n?'selected':''}>Up to $${n}</option>`).join('')}</select></label><label>Sort by<select id="catalog-sort"><option value="default">Recommended order</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="ram">Most memory</option></select></label></div><div class="filter-summary"><span id="result-count" role="status"></span><button class="text-button" type="button" id="clear-filters">Clear filters</button></div>`;
  }
  function filter(items,f) {
    const q=(f.q||'').toLowerCase().trim();
    return items.filter(p=>(!q||[p.name,p.specs,p.brand,p.os,p.cpu,p.gpu].join(' ').toLowerCase().includes(q))&&['brand','os','cpu','gpu'].every(k=>!f[k]||p[k]===f[k])&&(!f.budget||p.price<=Number(f.budget))&&(!f.item||p.id===f.item));
  }
  return {esc,card,filters,filter,options};
})();
